# Generated by Django 3.2.5 on 2022-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20220201_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
