# Generated by Django 3.2.5 on 2022-02-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_source_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='english',
            old_name='tags',
            new_name='tag',
        ),
    ]
