# Generated by Django 3.2.5 on 2022-02-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_alter_english_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Reference',
        ),
        migrations.RenameField(
            model_name='english',
            old_name='source',
            new_name='reference',
        ),
    ]
