# Generated by Django 3.2.5 on 2022-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_auto_20220204_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='note',
            new_name='publication',
        ),
        migrations.AddField(
            model_name='source',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
