# Generated by Django 3.2.5 on 2022-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_auto_20220204_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
