# Generated by Django 3.2.5 on 2022-02-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_source_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='type',
        ),
    ]
