# Generated by Django 3.2.5 on 2022-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_auto_20220204_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='root',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='sub01',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='sub02',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
