# Generated by Django 3.2.5 on 2022-02-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_auto_20220205_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='format',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
