# Generated by Django 3.2.5 on 2022-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_source_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='audio_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
