# Generated by Django 3.2.5 on 2022-02-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0015_auto_20220210_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('note', models.TextField(null=True)),
                ('english', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='english.english')),
                ('tag', models.ManyToManyField(null=True, related_name='for_element', to='english.Tag')),
            ],
        ),
    ]
