# Generated by Django 3.2.5 on 2022-02-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='english',
        ),
    ]
